[build]
rustflags = ["-C", "target-cpu=native"]

[alias]
mlog = "run --release --features mlog --bin mlog --"
mlogv32 = "run --release --features mlogv32 --bin mlogv32 --"
test-nostd = "test --no-default-features --features no_std,serde_alloc"
