[target.'cfg(not(target_arch = "wasm32"))']
rustflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", 'getrandom_backend="wasm_js"']

[alias]
mlog = "run --release --features mlog --bin mlog --"
mlogv32 = "run --release --features mlogv32 --bin mlogv32 --"
test-nostd = "test --no-default-features --features no_std,serde_alloc"
